name: Continuous Integration
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [8.x, 10.x, 11.x, 12.x]
    steps:
        - name: Checking out code
        uses: actions/checkout@v1
        with:
            fetch-depth: 1
        - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install Node modules
        run: npm i
      - name: Run lint command
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [8.x, 10.x, 11.x, 12.x]
    steps:
        - name: Checking out code
        uses: actions/checkout@v1
        with:
            fetch-depth: 1
        - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install Node modules
        run: npm i
      - name: Run test command
        run: npm run test
