name: Continuous Integration
on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node modules
        run: npm i

      - name: Run lint command
        run: npm run lint

      - name: Run test command
        run: npm run test
